name: test_rusty_circuits

on: [push]

jobs: 
  fmt:
    name: fmt
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3

      - name: Install Stable
        uses: dtolnay/rust-toolchain@stable
      - name: cargo fmt --check
        run: cargo fmt --check

  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3

      - name: Install Stable
        uses: dtolnay/rust-toolchain@stable
      - name: cargo clippy -- -D warnings
        run: cargo clippy -- -D warnings

  test: 
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Stable
        uses: dtolnay/rust-toolchain@stable
      - name: cargo test --all
        run: cargo test --all





