name: test_rusty_circuits

on: [push]

jobs: 
  test_rusty_circuits:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
      - uses: actions-rs/cargo@v1

      - name: Update local toolchain
        run: |
          rustup update
          rustup component add clippy

      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version

      - name: Lint
        run: |
          cargo clippy -- -D warnings

      - name: Test
        run: |
          cargo check
          cargo test --all




